[package]
name = "logs-of-war"
version = "0.1.0"
edition = "2024"

[dependencies]
avian3d = "0.6.0"
bevy = "0.18.1"
bevy_pkv = "0.15.0"
rand = "0.9"

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

[lints.clippy]
todo = "allow"
empty_loop = "forbid"
infinite_loop = "deny"
